import { useState, useEffect } from 'react';
import { suggestionsApi, sessionsApi, profileApi } from '@/lib/api';
import { useToast } from '@/components/ui/toast';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Zap, Sparkles, Save, User, RefreshCw, BarChart2 } from 'lucide-react';
import SessionForm from '@/components/forms/SessionForm';

const STATIONS = [
  { key: 'run',              label: 'Run'               },
  { key: 'skiErg',          label: 'SkiErg'            },
  { key: 'sledPush',        label: 'Sled Push'         },
  { key: 'sledPull',        label: 'Sled Pull'         },
  { key: 'burpeeBroadJump', label: 'Burpee Broad Jump' },
  { key: 'rowErg',          label: 'Row Erg'           },
  { key: 'farmersCarry',    label: 'Farmers Carry'     },
  { key: 'walkingLunges',   label: 'Walking Lunges'    },
  { key: 'wallBall',        label: 'Wall Ball'         },
];

function focusBarColor(score) {
  if (score >= 7) return 'bg-red-500';
  if (score >= 4) return 'bg-yellow-400';
  return 'bg-green-500';
}

export default function SuggestionTool() {
  const [form, setForm] = useState({
    location: '',
    equipment: '',
    focus: '',
    timeAvailable: '',
  });
  const [notes, setNotes] = useState('');
  const [profile, setProfile] = useState({ gender: '', birthday: '', trainingPatterns: '' });
  const [profileSaving, setProfileSaving] = useState(false);
  const [stationFocus, setStationFocus] = useState(null);
  const [focusLoading, setFocusLoading] = useState(false);
  const [suggestion, setSuggestion] = useState(null);
  const [loading, setLoading] = useState(false);
  const [showSaveForm, setShowSaveForm] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    profileApi.get().then(data => {
      setProfile({
        gender: data.gender || '',
        birthday: data.birthday || '',
        trainingPatterns: data.trainingPatterns || '',
      });
    }).catch(() => {});
    loadStationFocus();
  }, []);

  async function loadStationFocus() {
    setFocusLoading(true);
    try {
      const data = await suggestionsApi.stationFocus();
      setStationFocus(data);
    } catch {
      // silently ignore if AI unavailable
    } finally {
      setFocusLoading(false);
    }
  }

  const set = (k, v) => setForm(prev => ({ ...prev, [k]: v }));

  async function handleProfileSave() {
    setProfileSaving(true);
    try {
      await profileApi.update({
        gender: profile.gender || null,
        birthday: profile.birthday || null,
        trainingPatterns: profile.trainingPatterns || null,
      });
      toast({ title: 'Profile saved' });
    } catch {
      toast({ title: 'Error', description: 'Could not save profile.', variant: 'destructive' });
    } finally {
      setProfileSaving(false);
    }
  }

  async function handleGenerate() {
    if (!form.location || !form.equipment || !form.focus || !form.timeAvailable) {
      toast({ title: 'Fill in all fields', description: 'All options are required to generate a suggestion.', variant: 'destructive' });
      return;
    }
    setLoading(true);
    setSuggestion(null);
    try {
      const { suggestion: result } = await suggestionsApi.generate({ ...form, notes });
      setSuggestion(result);
    } catch (err) {
      toast({ title: 'Error', description: err.message, variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-6 max-w-3xl">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <Zap className="h-6 w-6 text-primary" />
          Training Suggestion
        </h1>
        <p className="text-muted-foreground text-sm">Get a personalised workout generated by your AI coach</p>
      </div>

      {/* Profile card */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <User className="h-4 w-4" />
            Your Profile
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <Label>Gender</Label>
              <Select value={profile.gender} onValueChange={v => setProfile(p => ({ ...p, gender: v }))}>
                <SelectTrigger><SelectValue placeholder="Select gender" /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="male">Male</SelectItem>
                  <SelectItem value="female">Female</SelectItem>
                  <SelectItem value="other">Other</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label>Date of birth</Label>
              <Input
                type="date"
                value={profile.birthday}
                onChange={e => setProfile(p => ({ ...p, birthday: e.target.value }))}
              />
            </div>
          </div>
          <div className="space-y-1.5">
            <Label>Training patterns & preferences <span className="text-muted-foreground font-normal">(optional)</span></Label>
            <textarea
              className="w-full min-h-[80px] rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring resize-y"
              placeholder="e.g. On Mondays I wait for my daughter at sport and do running intervals. Every 2 weeks I like to run stairs. I prefer morning sessions. I dislike treadmills..."
              value={profile.trainingPatterns}
              onChange={e => setProfile(p => ({ ...p, trainingPatterns: e.target.value }))}
            />
          </div>
          <Button onClick={handleProfileSave} disabled={profileSaving} variant="outline" size="sm">
            {profileSaving ? 'Saving…' : 'Save profile'}
          </Button>
        </CardContent>
      </Card>

      {/* Station focus bars */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between pb-2">
          <CardTitle className="text-base flex items-center gap-2">
            <BarChart2 className="h-4 w-4" />
            Training Focus
          </CardTitle>
          <Button
            variant="ghost"
            size="sm"
            onClick={loadStationFocus}
            disabled={focusLoading}
            className="gap-1 text-xs h-7 px-2 text-muted-foreground"
          >
            <RefreshCw className={`h-3 w-3 ${focusLoading ? 'animate-spin' : ''}`} />
            {focusLoading ? 'Analysing…' : 'Refresh'}
          </Button>
        </CardHeader>
        <CardContent>
          {focusLoading && !stationFocus && (
            <p className="text-xs text-muted-foreground">Analysing your training data…</p>
          )}
          {!focusLoading && !stationFocus && (
            <p className="text-xs text-muted-foreground">No analysis yet. Add some sessions and objectives first, then hit Refresh.</p>
          )}
          {stationFocus && (
            <div className="space-y-2">
              <p className="text-xs text-muted-foreground mb-3">Score 0–10 · Higher = needs more focus</p>
              {STATIONS.map(s => {
                const score = stationFocus[s.key] ?? 0;
                return (
                  <div key={s.key} className="flex items-center gap-3">
                    <span className="text-xs w-36 shrink-0">{s.label}</span>
                    <div className="flex-1 h-2 rounded-full bg-muted overflow-hidden">
                      <div
                        className={`h-full rounded-full transition-all ${focusBarColor(score)}`}
                        style={{ width: `${score * 10}%` }}
                      />
                    </div>
                    <span className={`text-xs font-bold w-6 text-right ${
                      score >= 7 ? 'text-red-400' : score >= 4 ? 'text-yellow-400' : 'text-green-400'
                    }`}>{score}</span>
                  </div>
                );
              })}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Session parameters + notes */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Tell me about today</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <Label>Where are you training?</Label>
              <Select value={form.location} onValueChange={v => set('location', v)}>
                <SelectTrigger><SelectValue placeholder="Location" /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="club_gym">Club Gym (full Hyrox setup)</SelectItem>
                  <SelectItem value="regular_gym">Regular Gym</SelectItem>
                  <SelectItem value="home">Home</SelectItem>
                  <SelectItem value="hotel">Hotel</SelectItem>
                  <SelectItem value="outdoor">Outdoor / Park</SelectItem>
                  <SelectItem value="track">Running Track</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label>Equipment available</Label>
              <Select value={form.equipment} onValueChange={v => set('equipment', v)}>
                <SelectTrigger><SelectValue placeholder="Equipment" /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="full_gym_hyrox">Full gym + Hyrox equipment</SelectItem>
                  <SelectItem value="full_gym">Full gym (barbells, racks, machines)</SelectItem>
                  <SelectItem value="limited">Limited (dumbbells, kettlebells, bands)</SelectItem>
                  <SelectItem value="running_only">Running only</SelectItem>
                  <SelectItem value="bodyweight">Bodyweight only</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label>Training focus</Label>
              <Select value={form.focus} onValueChange={v => set('focus', v)}>
                <SelectTrigger><SelectValue placeholder="Focus" /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="hyrox_race_simulation">Hyrox Race Simulation</SelectItem>
                  <SelectItem value="hyrox_strength">Hyrox Station Strength</SelectItem>
                  <SelectItem value="running_intervals">Running Intervals</SelectItem>
                  <SelectItem value="endurance_run">Endurance Run</SelectItem>
                  <SelectItem value="gym_strength">Gym Strength</SelectItem>
                  <SelectItem value="mixed">Mixed (strength + cardio)</SelectItem>
                  <SelectItem value="recovery">Active Recovery</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label>Time available</Label>
              <Select value={form.timeAvailable} onValueChange={v => set('timeAvailable', v)}>
                <SelectTrigger><SelectValue placeholder="Duration" /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="30">30 minutes</SelectItem>
                  <SelectItem value="45">45 minutes</SelectItem>
                  <SelectItem value="60">60 minutes</SelectItem>
                  <SelectItem value="75">75 minutes</SelectItem>
                  <SelectItem value="90">90 minutes</SelectItem>
                  <SelectItem value="120">2 hours</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-1.5">
            <Label>Anything relevant today? <span className="text-muted-foreground font-normal">(optional)</span></Label>
            <textarea
              className="w-full min-h-[80px] rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring resize-y"
              placeholder="e.g. My left knee is a bit sore, only squat rack available today, feeling tired from yesterday's long run…"
              value={notes}
              onChange={e => setNotes(e.target.value)}
            />
          </div>

          <Button onClick={handleGenerate} disabled={loading} className="w-full gap-2" size="lg">
            {loading ? (
              <>
                <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                Generating your workout...
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4" />
                Generate Training Session
              </>
            )}
          </Button>
        </CardContent>
      </Card>

      {suggestion && (
        <Card className="border-primary/20 bg-primary/5">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-base flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-primary" />
              Your AI-Coached Workout
            </CardTitle>
            <Button onClick={() => setShowSaveForm(true)} variant="outline" size="sm" className="gap-2">
              <Save className="h-4 w-4" /> Save as Planned Session
            </Button>
          </CardHeader>
          <CardContent>
            <div className="ai-content text-sm leading-relaxed whitespace-pre-wrap">
              {suggestion}
            </div>
          </CardContent>
        </Card>
      )}

      {showSaveForm && (
        <SessionForm
          session={{
            type: mapFocusToType(form.focus),
            status: 'planned',
            location: form.location,
            equipment: form.equipment,
            duration: parseInt(form.timeAvailable),
            notes: suggestion || '',
          }}
          onClose={() => setShowSaveForm(false)}
          onSaved={() => {
            setShowSaveForm(false);
            toast({ title: 'Saved!', description: 'Workout saved as a planned session.' });
          }}
        />
      )}
    </div>
  );
}

function mapFocusToType(focus) {
  if (!focus) return 'hyrox_training';
  if (focus.includes('running') || focus.includes('run')) return 'running';
  if (focus === 'gym_strength') return 'gym_strength';
  if (focus === 'recovery') return 'recovery';
  return 'hyrox_training';
}
