import { useState } from 'react';
import { suggestionsApi, sessionsApi } from '@/lib/api';
import { useToast } from '@/components/ui/toast';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Zap, Sparkles, Save } from 'lucide-react';
import SessionForm from '@/components/forms/SessionForm';

export default function SuggestionTool() {
  const [form, setForm] = useState({
    location: '',
    equipment: '',
    focus: '',
    timeAvailable: '',
  });
  const [suggestion, setSuggestion] = useState(null);
  const [loading, setLoading] = useState(false);
  const [showSaveForm, setShowSaveForm] = useState(false);
  const { toast } = useToast();

  const set = (k, v) => setForm(prev => ({ ...prev, [k]: v }));

  async function handleGenerate() {
    if (!form.location || !form.equipment || !form.focus || !form.timeAvailable) {
      toast({ title: 'Fill in all fields', description: 'All options are required to generate a suggestion.', variant: 'destructive' });
      return;
    }
    setLoading(true);
    setSuggestion(null);
    try {
      const { suggestion: result } = await suggestionsApi.generate(form);
      setSuggestion(result);
    } catch (err) {
      toast({ title: 'Error', description: err.message, variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-6 max-w-3xl">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <Zap className="h-6 w-6 text-primary" />
          Training Suggestion
        </h1>
        <p className="text-muted-foreground text-sm">Get a personalised workout generated by your AI coach</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Tell me about today</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <Label>Where are you training?</Label>
              <Select value={form.location} onValueChange={v => set('location', v)}>
                <SelectTrigger><SelectValue placeholder="Location" /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="club_gym">Club Gym (full Hyrox setup)</SelectItem>
                  <SelectItem value="regular_gym">Regular Gym</SelectItem>
                  <SelectItem value="home">Home</SelectItem>
                  <SelectItem value="hotel">Hotel</SelectItem>
                  <SelectItem value="outdoor">Outdoor / Park</SelectItem>
                  <SelectItem value="track">Running Track</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label>Equipment available</Label>
              <Select value={form.equipment} onValueChange={v => set('equipment', v)}>
                <SelectTrigger><SelectValue placeholder="Equipment" /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="full_gym_hyrox">Full gym + Hyrox equipment</SelectItem>
                  <SelectItem value="full_gym">Full gym (barbells, racks, machines)</SelectItem>
                  <SelectItem value="limited">Limited (dumbbells, kettlebells, bands)</SelectItem>
                  <SelectItem value="running_only">Running only</SelectItem>
                  <SelectItem value="bodyweight">Bodyweight only</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label>Training focus</Label>
              <Select value={form.focus} onValueChange={v => set('focus', v)}>
                <SelectTrigger><SelectValue placeholder="Focus" /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="hyrox_race_simulation">Hyrox Race Simulation</SelectItem>
                  <SelectItem value="hyrox_strength">Hyrox Station Strength</SelectItem>
                  <SelectItem value="running_intervals">Running Intervals</SelectItem>
                  <SelectItem value="endurance_run">Endurance Run</SelectItem>
                  <SelectItem value="gym_strength">Gym Strength</SelectItem>
                  <SelectItem value="mixed">Mixed (strength + cardio)</SelectItem>
                  <SelectItem value="recovery">Active Recovery</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label>Time available</Label>
              <Select value={form.timeAvailable} onValueChange={v => set('timeAvailable', v)}>
                <SelectTrigger><SelectValue placeholder="Duration" /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="30">30 minutes</SelectItem>
                  <SelectItem value="45">45 minutes</SelectItem>
                  <SelectItem value="60">60 minutes</SelectItem>
                  <SelectItem value="75">75 minutes</SelectItem>
                  <SelectItem value="90">90 minutes</SelectItem>
                  <SelectItem value="120">2 hours</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <Button onClick={handleGenerate} disabled={loading} className="w-full gap-2" size="lg">
            {loading ? (
              <>
                <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                Generating your workout...
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4" />
                Generate Training Session
              </>
            )}
          </Button>
        </CardContent>
      </Card>

      {suggestion && (
        <Card className="border-primary/20 bg-primary/5">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-base flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-primary" />
              Your AI-Coached Workout
            </CardTitle>
            <Button onClick={() => setShowSaveForm(true)} variant="outline" size="sm" className="gap-2">
              <Save className="h-4 w-4" /> Save as Planned Session
            </Button>
          </CardHeader>
          <CardContent>
            <div className="ai-content text-sm leading-relaxed whitespace-pre-wrap">
              {suggestion}
            </div>
          </CardContent>
        </Card>
      )}

      {showSaveForm && (
        <SessionForm
          session={{
            type: mapFocusToType(form.focus),
            status: 'planned',
            location: form.location,
            equipment: form.equipment,
            duration: parseInt(form.timeAvailable),
            notes: suggestion || '',
          }}
          onClose={() => setShowSaveForm(false)}
          onSaved={() => {
            setShowSaveForm(false);
            toast({ title: 'Saved!', description: 'Workout saved as a planned session.' });
          }}
        />
      )}
    </div>
  );
}

function mapFocusToType(focus) {
  if (!focus) return 'hyrox_training';
  if (focus.includes('running') || focus.includes('run')) return 'running';
  if (focus === 'gym_strength') return 'gym_strength';
  if (focus === 'recovery') return 'recovery';
  return 'hyrox_training';
}
